//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnLLWP.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tTryPetTable
    {
        public int fTryPetId { get; set; }
        public string fTryPetNum { get; set; }
        public string fTryPetName { get; set; }
        public string fTryPetVar { get; set; }
        public int fTryPetAge { get; set; }
        public double fTryPetWei { get; set; }
        public string fTryPetSex { get; set; }
        public string fTryPetNature { get; set; }
        public string fTryPetVac { get; set; }
        public string fTryPetFix { get; set; }
        public string fTryPetPhoto { get; set; }
        public HttpPostedFileBase fImage{ get; set; }
}
}
